# Generated by Django 4.2.13 on 2026-04-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("rule_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("query", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("not_applicable", "Not Applicable"),
                            ("applicable", "Applicable"),
                            ("in_progress", "In Progress"),
                            ("ready_for_cb", "Ready for CB"),
                            ("converted", "Converted"),
                            ("active", "Active"),
                            ("tuning", "Tuning"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("assigned_analyst", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_escu_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cb_conversions",
                        to="escu.escurule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CBRuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="carbonblack.cbrule",
                    ),
                ),
            ],
        ),
    ]
