# Generated by Django 4.2.13 on 2026-04-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ESCUImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="uploads/escu/")),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("rules_added", models.IntegerField(default=0)),
                ("rules_updated", models.IntegerField(default=0)),
                ("rules_deprecated", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ESCURule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("rule_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("mitre_tactic", models.CharField(blank=True, max_length=255)),
                ("mitre_technique", models.CharField(blank=True, max_length=255)),
                ("mitre_technique_id", models.CharField(blank=True, max_length=50)),
                ("severity", models.CharField(blank=True, max_length=50)),
                ("search", models.TextField(blank=True)),
                ("data_source", models.CharField(blank=True, max_length=255)),
                ("raw_csv_row", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("not_applicable", "Not Applicable"),
                            ("applicable", "Applicable"),
                            ("in_progress", "In Progress"),
                            ("ready_for_cb", "Ready for CB"),
                            ("converted", "Converted"),
                            ("active", "Active"),
                            ("tuning", "Tuning"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("assigned_analyst", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_seen_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_rules",
                        to="escu.escuimportbatch",
                    ),
                ),
                (
                    "last_seen_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seen_rules",
                        to="escu.escuimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ESCURuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("change_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escu.escuimportbatch",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="escu.escurule",
                    ),
                ),
            ],
        ),
    ]
