# Generated by Django 4.2.13 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("import", "Import"),
                            ("assign", "Assign"),
                            ("stage_change", "Stage Change"),
                            ("convert", "Convert"),
                            ("export", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.IntegerField()),
                ("entity_label", models.CharField(max_length=255)),
                ("actor_name", models.CharField(default="system", max_length=150)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            (
                                "env_data_sources",
                                "Ortamda Bulunan Veri Kaynakları (virgülle)",
                            ),
                            ("env_os_types", "Ortamda Bulunan OS Tipleri (virgülle)"),
                            (
                                "env_mitre_focus",
                                "Öncelikli MITRE Tactic'ler (virgülle)",
                            ),
                            (
                                "similarity_threshold",
                                "Benzer Kural Eşiği (0-100, varsayılan 70)",
                            ),
                            ("default_analyst", "Varsayılan Atanan Analist"),
                            (
                                "export_columns_escu",
                                "CSV Export'a Dahil Edilecek ESCU Kolonlar",
                            ),
                            (
                                "export_columns_cb",
                                "CSV Export'a Dahil Edilecek CB Kolonlar",
                            ),
                            ("review_sla_days", "İnceleme SLA Günü (varsayılan 14)"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
