# Generated by Django 4.2.13 on 2026-04-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escu", "0001_initial"),
        ("carbonblack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compare_type", models.CharField(max_length=10)),
                ("rule_a_id", models.IntegerField()),
                ("rule_a_label", models.CharField(max_length=500)),
                ("rule_b_id", models.IntegerField()),
                ("rule_b_label", models.CharField(max_length=500)),
                ("score", models.FloatField()),
                ("match_fields", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="RuleConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adaptation_notes", models.TextField(blank=True)),
                ("cb_query_draft", models.TextField(blank=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "cb_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_record",
                        to="carbonblack.cbrule",
                    ),
                ),
                (
                    "escu_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="escu.escurule",
                    ),
                ),
            ],
        ),
    ]
